vle:
  pretrained_weights_root_path: '/home/olivieri/exp/data/private/huggingface/hub/flair'
  image_size: 224

seg:
  image_size: 520

mask_prs_path: '/home/olivieri/exp/data/private/prompts_data/by_model/LRASPP_MobileNet_V3/_mask_prs_'
